from app import db
from models import Cell, Favcell, Item, User

#this script generates objects and then adds them to the database so there is some preexisting data
f1 = Favcell(id = 3456)
f2 = Favcell(id = 2342)
f3 = Favcell(id = 4576)
f4 = Favcell(id = 8743)
u1 = User(id = 1, username = "whtebldcellf4n", favcell_id = f1.id)
u2 = User(id = 2, username = "biologyrocks", favcell_id = f2.id)
u3 = User(id = 3, username = "dermatologist", favcell_id = f3.id)
u4 = User(id = 4, username = "billnye", favcell_id = f4.id)

c1 = Cell(id = 1, cellgroup = "Red blood cell", cellname = "Erythrocytes", n = 0)
c2 = Cell(id = 2, cellgroup = "Skin cell", cellname = "Keratinocytes", n = 0)
c3 = Cell(id = 3, cellgroup = "Skin cell", cellname = "Melanocytes", n = 0)
c4 = Cell(id = 4, cellgroup = "Skin cell", cellname = "Merkel cells", n = 0) 
c5 = Cell(id = 5, cellgroup = "Skin cell", cellname = "Langerhans cells", n = 0)
c6 = Cell(id = 6, cellgroup = "White blood cell", cellname = "Granulocytes", n = 0)
c7 = Cell(id = 7, cellgroup = "White blood cell", cellname = "Agranulocytes", n = 0)
c8 = Cell(id = 8, cellgroup = "Stem cell", cellname = "Embryonic", n = 0)
c9 = Cell(id = 9, cellgroup = "Stem cell", cellname = "Adult", n = 0)
c10 = Cell(id = 10, cellgroup = "Muscle cell", cellname = "Skeletal", n = 0)
c11 = Cell(id = 11, cellgroup = "Muscle cell", cellname = "Cardiac", n = 0)
c12 = Cell(id = 12, cellgroup = "Muscle cell", cellname = "Smooth", n = 0)

db.session.add(f1)
db.session.add(f2)
db.session.add(f3)
db.session.add(f4)
db.session.add(u1)
db.session.add(u2)
db.session.add(u3)
db.session.add(u4)
db.session.add(c1)
db.session.add(c2)
db.session.add(c3)
db.session.add(c4)
db.session.add(c5)
db.session.add(c6)
db.session.add(c7)
db.session.add(c8)
db.session.add(c9)
db.session.add(c10)
db.session.add(c11)
db.session.add(c12)
db.session.commit()
